name: Test

on:
  pull_request:
     branches:
       - '*'
  push:
     branches:
       - '*'

env:
  GH_REF: ${{ github.ref }}
  GH_HEAD_REF: ${{ github.head_ref }}

jobs:
  branchname:
    runs-on: ubuntu-18.04
    steps: [
      { name: 'Checkout', uses: actions/checkout@v2 },
      {
        name: 'Branch name from env',
        shell: bash,
        run: 'echo "GITHUB_REF_NAME = ${GITHUB_REF_NAME} GH_HEAD_REF = ${GH_HEAD_REF} GH_REF = ${GH_REF}"'
      },
      {
        name: 'Branch name from git rev-parse',
        shell: bash,
        run: 'git rev-parse --abbrev-ref HEAD'
      },
      {
        name: 'Branch name from git show-current',
        shell: bash,
        run: 'git branch --show-current'
      }]
